"""Generate a starter labelman.yaml from existing label sidecars.

`labelman build` walks a directory's final-label sidecars (`*.txt` and
`*.mb`, excluding the intermediate `*.labels.*` and `*.detected.*` files),
collects the unique label set, and emits a flat YAML in which every term
is its own zero-or-one category. The user clusters from there.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from .label import MB_FORMAT, TXT_FORMAT, SidecarFormat


_HEADER_TEMPLATE = """\
# labelman.yaml — generated by `labelman build` on {today}.
#
# Each unique term collected from existing .txt and .mb sidecars in this
# directory has been placed in its own zero-or-one category. Edit this
# file to cluster related terms (e.g. all colors under one category),
# change a category's mode, or add thresholds. Comments above this line
# are preserved across regenerations only if you re-run `build` with
# --force; consider keeping clustering work in a separate file.
"""


def _is_intermediate(name: str) -> bool:
    """True for *.labels.<ext> and *.detected.<ext> sidecars."""
    return (
        name.endswith(".labels.txt")
        or name.endswith(".detected.txt")
        or name.endswith(".labels.mb")
        or name.endswith(".detected.mb")
    )


def _format_for(suffix: str) -> SidecarFormat | None:
    if suffix == ".txt":
        return TXT_FORMAT
    if suffix == ".mb":
        return MB_FORMAT
    return None


def collect_terms(images_dir: Path) -> tuple[list[str], int]:
    """Scan images_dir for final-label sidecars and return (sorted_unique_terms, files_scanned).

    Reads plain ``*.txt`` and ``*.mb`` files (skipping ``*.labels.*`` and
    ``*.detected.*``). Each file is decoded with the matching SidecarFormat
    so commas and semicolons are handled correctly per format.
    """
    terms: set[str] = set()
    files_scanned = 0
    for path in sorted(images_dir.iterdir()):
        if not path.is_file():
            continue
        if _is_intermediate(path.name):
            continue
        fmt = _format_for(path.suffix.lower())
        if fmt is None:
            continue
        files_scanned += 1
        for label in fmt.decode(path.read_text()):
            # Suppression directives ("-foo") are an artifact of manual
            # sidecars; in a final sidecar they should not appear, but
            # filter defensively just in case.
            if label.startswith("-"):
                continue
            terms.add(label)
    return sorted(terms), files_scanned


def render_yaml(terms: list[str]) -> str:
    """Render a minimal labelman.yaml string from a sorted term list.

    Comments at the top, ``defaults:`` and ``categories:`` at the bottom.
    Each term becomes a single-term zero-or-one category.
    """
    lines: list[str] = [_HEADER_TEMPLATE.format(today=date.today().isoformat())]
    lines.append("defaults:")
    lines.append("  threshold: 0.3")
    lines.append("")
    lines.append("categories:")
    for term in terms:
        lines.append(f"  - name: {_yaml_scalar(term)}")
        lines.append(f"    mode: zero-or-one")
        lines.append(f"    terms:")
        lines.append(f"      - term: {_yaml_scalar(term)}")
    lines.append("")
    return "\n".join(lines)


def _yaml_scalar(s: str) -> str:
    """Quote a YAML scalar when needed.

    Conservative: any term containing a YAML special character or leading/
    trailing whitespace is double-quoted with embedded quotes escaped.
    Unambiguous bare words (alphanumerics, dashes, underscores, dots) are
    emitted as-is so the file stays readable.
    """
    if s and all(c.isalnum() or c in "-_.+" for c in s) and not s[0].isdigit():
        return s
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build_yaml(images_dir: Path) -> tuple[str, list[str], int]:
    """Build the YAML text and return (text, terms, files_scanned).

    The returned ``files_scanned`` counts qualifying sidecar files (not
    images). ``terms`` may be empty — the caller decides whether that is
    an error worth surfacing.
    """
    terms, files_scanned = collect_terms(images_dir)
    text = render_yaml(terms) if terms else ""
    return text, terms, files_scanned
